export const URLs= {
    BASE_URL: 'http://localhost:8080/api',
    LOGIN: '/v1/auth/login',
    REGISTER: '/auth/register',
    CREATE_POST: (userId:string,categoryId:string)=>`/user/${userId}/category/${categoryId}/posts`,
    GET_POSTS: '/posts',
    GET_POST_BY_ID: (id: string) => `/posts/${id}`,
    GET_POSTS_BY_USER:(userId:string)=>`/user/${userId}/posts`,
    UPDATE_POST: (id: string) => `/posts/${id}`,
    DELETE_POST: (id: string) => `/posts/${id}`,
    CREATE_USER: '/users',
    GET_USERS: '/users',
    GET_USER_BY_ID: (id: string) => `/users/${id}`,
    UPDATE_USER: (id: string) => `/users/${id}`,
    DELETE_USER: (id: string) => `/users/${id}`,
    UPLOAD_IMAGE: (postId:string)=>`/posts/image/upload/${postId}`,
    CREATE_COMMENT: (postId:string,userId:string)=>`/comments/post/${postId}/user/${userId}`,
    DELETE_COMMENT: (id: string) => `/comments/${id}`,
}
